const ActionType = {
  MACHINE_CONNECT: 'MACHINE_CONNECT',
  MACHINE_ACCEPTED: 'MACHINE_ACCEPTED',
  MACHINE_REJECTED: 'MACHINE_REJECTED',
  MACHINE_START: 'MACHINE_START',
  MACHINE_STARTED: 'MACHINE_STARTED',
  MACHINE_STOP: 'MACHINE_STOP',
  MACHINE_STOPPED: 'MACHINE_STOPPED',
};

export default ActionType;
